name: PHPUnit
on:
  workflow_call:
    inputs:
      extensionName:
        description: 'Your extension name'
        required: true
        type: string
      shopwareVersion:
        required: false
        type: string
        default: 'trunk'
      uploadCoverage:
        description: 'Upload coverage to codecov'
        required: false
        type: boolean
        default: false
    secrets:
      codecovToken:
        description: 'Codecov token'
        required: false
jobs:
  run:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Shopware
        uses: FriendsOfShopware/setup-shopware@main
        with:
          shopware-version: ${{ inputs.shopwareVersion }}
          php-version: 8.2
          php-extensions: pcov
      - name: Clone Extension
        uses: actions/checkout@v4
        with:
          path: custom/plugins/${{ inputs.extensionName }}
      - name: Run PHPUnit
        working-directory: custom/plugins/${{ inputs.extensionName }}
        run: ${{ github.workspace }}/vendor/bin/phpunit --coverage-clover clover.xml
      - name: Upload Coverage
        if: inputs.uploadCoverage == true
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.codecovToken }}
        with:
          root_dir: ${{ github.workspace }}/custom/plugins/${{ inputs.extensionName }}
          working-directory: ${{ github.workspace }}/custom/plugins/${{ inputs.extensionName }}
          files: ./clover.xml
